services:
  - type: web
    name: pokedex
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

